name: Bundle Remotion studio
on: 
  workflow_dispatch:
  push:
    branches:
      - 'main'
permissions:
  contents: write
jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - name: Checkout & setup
        uses: actions/checkout@main
        
      - uses: oven-sh/setup-bun
      - run: sudo apt update
      
      - name: install packages
        run: bun i

      - name: Bundle studio
        run: bunx remotion bundle

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
