name: Bundle Remotion studio
on: 
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - name: Checkout & setup
        uses: actions/checkout@main
        
      - uses: actions/setup-node@main
      - run: sudo apt update
      
      - name: install packages
        run: npm i

      - name: Bundle studio
        run: npx remotion bundle

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
